### ISSUE TITLE
[Enhancement]: 音声認識

### ISSUE THREAD

**Issue by yaakiyu** [RextTeam/rt-bot#135]
### Please asked me.

freeRTにあった機能。
coding by ysmreg
ボイスチャンネルの音声を録音し、認識し、文字起こしした上で、RTに対する音声式コマンドを実行できる。

**Comment by tuna2134** [comment]
これいる？
いらないと思うよ

**Comment by yaakiyu** [comment]
freeRTにあった機能は一応issue立てるだけ立てておく。
いらなかったらそっちで消臭してほしい。

**Comment by tuna2134** [comment]
> freeRTにあった機能は一応issue立てるだけ立てておく。
> いらなかったらそっちで消臭してほしい。

負荷もどうなの？

**Comment by tuna2134** [comment]
音声認識は結構負担かかるはずだから却下で(もしもやるならDeepl)

**Comment by tuna2134** [comment]
もしくはApiとして用意するなら考える

**Comment by ysmreg** [comment]
> > freeRTにあった機能は一応issue立てるだけ立てておく。
> > いらなかったらそっちで消臭してほしい。
> 
> 負荷もどうなの？

私が実行したときは負荷はあまりかかりませんでした。メモリとCPUで確認

**Comment by tuna2134** [comment]
> > > freeRTにあった機能は一応issue立てるだけ立てておく。
> > > いらなかったらそっちで消臭してほしい。
> > 
> > 
> > 負荷もどうなの？
> 
> 私が実行したときは負荷はあまりかかりませんでした。メモリとCPUで確認

何を使うのかね？(ライブラリ)

**Comment by tuna2134** [comment]
出来るだけ優先してほしいのは旧RTにあるやつ

**Comment by tuna2134** [comment]
Googleのapiとか使うのもいいけど
あと音声認識需要が見込めない
コマンド実行はテキストチャンネルで実行すればいい

**Comment by ysmreg** [comment]
> > > > freeRTにあった機能は一応issue立てるだけ立てておく。
> > > > いらなかったらそっちで消臭してほしい。
> > > 
> > > 
> > > 負荷もどうなの？
> > 
> > 私が実行したときは負荷はあまりかかりませんでした。メモリとCPUで確認
> 
> 何を使うのかね？(ライブラリ)

ライブラリはpyopenjtalk、libopus，juliusだね

**Comment by tuna2134** [comment]
> > > > > freeRTにあった機能は一応issue立てるだけ立てておく。
> > > > > いらなかったらそっちで消臭してほしい。
> > > > 
> > > > 
> > > > 負荷もどうなの？
> > > 
> > > 
> > > 私が実行したときは負荷はあまりかかりませんでした。メモリとCPUで確認
> > 
> > 
> > 何を使うのかね？(ライブラリ)
> 
> ライブラリはpyopenjtalk、libopus，juliusだね

pyopenjtalk
なんか入れようとしたら入らんかったなあ
