### ISSUE TITLE
[Bug]: cleaner

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#155]
### What happened?

しらね

### Version

- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4374+g7ad00750
- aiohttp v3.8.1
- system info: Linux 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022

### Relevant log output

```shell
6月 26 18:04:44 mc-fdc.f5.si python[1967]: [RT.Bot] [Cleaner] /home/rocky/rt/rt-bot/rtlib/common/database.py:100: RuntimeWarning: c>
 6月 26 18:04:44 mc-fdc.f5.si python[1967]:   if self.not_exists_check_for_clean(type_, row[0]):
 6月 26 18:04:44 mc-fdc.f5.si python[1967]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by tasuren** [comment]
これはrtlibで問題がある。
ただの`await`し忘れ。

**Comment by tasuren** [comment]
修正した。
