### ISSUE TITLE
`bot.get_...`使用時に警告を出すようにする。

### ISSUE THREAD

**Issue by tasuren** [RextTeam/rt-bot#159]
タイトル通り。
`bot.search_...`を使うように要請する。

**Comment by ysmreg** [comment]
これなら出来そう。Botを継承したクラスがあればだけど

**Comment by tasuren** [comment]
Yeah
`Bot`を継承したクラス`RT`に実装すれば良い。

**Comment by ysmreg** [comment]
これやって見る

**Comment by tasuren** [comment]
warnライブラリ使ってね。
そして、warnライブラリなら警告箇所表示できるから、警告発生箇所表示するようにしてね。

**Comment by ysmreg** [comment]
warn libって標準のパッケージかな

**Comment by ysmreg** [comment]
lib/warnings

**Comment by tasuren** [comment]
そうそれ

**Comment by tasuren** [comment]
@ysmreg warn関数のstacklevelっていう引数使って警告の原因となったかしぃが正しく表示されるようにして欲しい。

**Comment by ysmreg** [comment]
stacklevel使った事ないから調べながらやってみる

**Comment by tasuren** [comment]
とりあえず0,1,2,3くらい数上げてけば恐らくできる。

**Comment by ysmreg** [comment]
なるほど

**Comment by tasuren** [comment]
ysmreg氏によって実装されたためCloseする。
