### ISSUE TITLE
ENV_TOKENとかしているすると環境変数から取得する

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#160]
### Please asked me.

secret.jsonにトークンだったらENV_TOKENってやると、環境変数からトークンを取得する

**Comment by tasuren** [comment]
なんでそうするの？

**Comment by yaakiyu** [comment]
fdc氏がこのissueたてた理由とは違うかもしれないけど、僕の意見を。
もしsecret.jsonの名前を間違えてsacret.jsonとかやってて
そのままcommitしてgithubにでもあげちゃったら大変なことになると思う
env環境構築できるところではなるべくenvを使う方がいいと思う

**Comment by tasuren** [comment]
w, wow

**Comment by tuna2134** [comment]
> なんでそうするの？

Github codespaces使う際に、トークンの設定とかをしずに開発しやすくするため

**Comment by tasuren** [comment]
そっちの方が設定しやすいとかあるの？

**Comment by tuna2134** [comment]
わざわざjsonに書き込む必要がなくなる

**Comment by ysmreg** [comment]
envでもjsonでも、どっちもファイルに書き込むんだからどっちにしても変わらなそうって思ったenvは.envに書き込む必要あるし

**Comment by yaakiyu** [comment]
.envに書き込むならさらに`dotenv.load_dotenv()`が必要になる

**Comment by yaakiyu** [comment]
envは普通に「環境変数」だから、ファイル書き込みとはちょっと違うね
中身はただのファイルだけど()

**Comment by tasuren** [comment]
> fdc氏がこのissueたてた理由とは違うかもしれないけど、僕の意見を。
> もしsecret.jsonの名前を間違えてsacret.jsonとかやってて
> そのままcommitしてgithubにでもあげちゃったら大変なことになると思う
> env環境構築できるところではなるべくenvを使う方がいいと思う

もうこれは解決した。
`.gitignore`に`*.toml`ってやったから、名前間違えてやって`git add .`ってやってもcommitすることはない。
だから、意図してやらない限りGitHubに上げることはないようになった。

**Comment by tasuren** [comment]
ミスって閉じちゃった。

**Comment by tasuren** [comment]
@tuna2134 
もう`toml`でいいよね？
シンプルだしコメント簡単につけれるしわかりやすいし。

**Comment by tuna2134** [comment]
> @tuna2134
> もう`toml`でいいよね？
> シンプルだしコメント簡単につけれるしわかりやすいし。

まあいいけど

**Comment by tasuren** [comment]
Okay
