### ISSUE TITLE
[Enhancement]: CLIからRTのテストをできるようにする

### ISSUE THREAD

**Issue by yaakiyu** [RextTeam/rt-bot#161]
### Please asked me.

~~(僕が学校でテストするためだけの機能)~~
RTのテスト(コマンドの実行など)をコマンドラインインターフェースからできたらうれしいなぁって
自分でそういうテストできるライブラリつくると思う。

**Comment by tasuren** [comment]
ライブラリ作るならpytestのd.py対応版としてdpytestっていうライブラリ作れば？
って言おうと思ったが、既にあった。
https://dpytest.readthedocs.io/en/latest/
みな考えること同じか。w

**Comment by yaakiyu** [comment]
discord-testでいいや(適当)

**Comment by tasuren** [comment]
dpytest使わないの？

**Comment by yaakiyu** [comment]
ちょっと違うんだよね
CLIをそのままdiscordのチャンネルみたいに使ってもっと柔軟にテストしてみたい

**Comment by tasuren** [comment]
W,wow

**Comment by kousakirai** [comment]
aiotterさんが似たようなもの作ってたはず
ddiscordだっけな
https://github.com/aiotter/ddiscord また趣向は違うけどCLIからBotのデバッグができるやつ。
これをベースに改造してみたら？

**Comment by yaakiyu** [comment]
それを知っててちょっと違う仕組みのもの使ってみようと思って

**Comment by kousakirai** [comment]
ありゃ知ってたか。まあがんばえー

**Comment by yaakiyu** [comment]
できるようになりました。
