### ISSUE TITLE
[Others]: devonさんからの指摘シリーズ

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#172]
### describe

https://github.com/RextTeam/rt-bot/blob/main/core/bot.py#L197-L201
collections.defaultdictにしたほうがいいらしい。

https://github.com/RextTeam/rt-bot/blob/main/core/bot.py#L104-L106
logging使ったほうがいいみたい

**Comment by tuna2134** [comment]
![](https://cdn.discordapp.com/attachments/805459155611156510/994606593209536552/unknown.png)

**Comment by tuna2134** [comment]
https://github.com/RextTeam/rt-bot/blob/main/core/bot.py#L271
f"{self.latency * 1000:.1f}"

**Comment by tasuren** [comment]
バグは治す。
これはバグになる可能性があるの？

**Comment by tasuren** [comment]
バグじゃなくても変えるとしたらpathlibのやつだけかな。

**Comment by tuna2134** [comment]
> バグなら治すよ。
> pathlibとログ出力のやつはバグじゃなくても変えるかな。
> この中にバグになるのは何？

さあ？
でもやった方が効率がいいやつを教えてもらった

**Comment by tuna2134** [comment]
> バグなら治すよ。
> pathlibとログ出力のやつはバグじゃなくても変えるかな。
> この中にバグになるのは何？

ログ出力はデボンさんによるとライブラリの挙動も監視できるから使った方がいいみたい

**Comment by tasuren** [comment]
> > バグなら治すよ。
> > pathlibとログ出力のやつはバグじゃなくても変えるかな。
> > この中にバグになるのは何？
> 
> さあ？
> でもやった方が効率がいいやつを教えてもらった

どれに対して言ってる？
全部？

**Comment by tasuren** [comment]
ライブラリの監視ってd.pyのこと？

**Comment by tasuren** [comment]
> > > > > > バグなら治すよ。
> > > > > > pathlibとログ出力のやつはバグじゃなくても変えるかな。
> > > > > > この中にバグになるのは何？
> > > > > 
> > > > > 
> > > > > さあ？
> > > > > でもやった方が効率がいいやつを教えてもらった
> > > > 
> > > > 
> > > > どれに対して言ってる？ 全部？
> > > 
> > > 
> > > 全部
> > 
> > 本当に効率良くなるの？
> 
> 多分

多分ってのは君の感想？
Devonさんが多分って言う気がしない。

**Comment by tasuren** [comment]
あと僕はスパゲッティとは思ってないからな。(定期)

**Comment by yaakiyu** [comment]
dpyに限らずだと思う
loggingはprintよりも細かくいろんなこと制御できるからね

**Comment by tuna2134** [comment]
- うん

**Comment by tuna2134** [comment]
> > > > > > > バグなら治すよ。
> > > > > > > pathlibとログ出力のやつはバグじゃなくても変えるかな。
> > > > > > > この中にバグになるのは何？
> > > > > > 
> > > > > > 
> > > > > > さあ？
> > > > > > でもやった方が効率がいいやつを教えてもらった
> > > > > 
> > > > > 
> > > > > どれに対して言ってる？ 全部？
> > > > 
> > > > 
> > > > 全部
> > > 
> > > 
> > > 本当に効率良くなるの？
> > 
> > 
> > 多分
> 
> 多分ってのは君の感想？ Devonさんが多分って言う気がしない。

僕の感想です。
今度聞いてみるわ

**Comment by tuna2134** [comment]
https://discord.com/channels/718641964672876614/805459155611156510/994612148938473535

**Comment by tasuren** [comment]
loggingに関しては前々から変えたいと思ってた。
この際変えるか。

**Comment by tasuren** [comment]
じゃあそれ以外はとりあえず保留ということで。
もし変えたいなら理由と一緒にissue作ってくれ。

**Comment by tuna2134** [comment]
> じゃあそれ以外はとりあえず保留ということで。
> もし変えたいなら理由と一緒にissue作ってくれ。
> このissueに複数の事柄があるのはわかりずらい。

printとかは？

**Comment by yaakiyu** [comment]
printをloggingにする話以外は一つずつ別途issue立てろってことじゃね

**Comment by tasuren** [comment]
loggingは僕が変えたいと思ってたことだから、僕がさっきissue作った。
> printをloggingにする話以外は一つずつ別途issue立てろってことじゃね

それであってる。
