### ISSUE TITLE
募集パネル

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#29]

**Comment by tasuren** [comment]
ボタンで参加と参加取り消しを切り替える。
埋め込みにはタイトルと説明そして有効期限のフィールド(タイムスタンプを使用して表示)と参加者を表示するフィールドを作る。(参加者フィールドは収まらないのなら`...`を最後に付ける。)

**Comment by tasuren** [comment]
開発中...

**Comment by tasuren** [comment]
実装した。
