### ISSUE TITLE
ブロッカー機能

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#43]
* [ ] 絵文字
* [ ] スタンプ

**Comment by yaakiyu** [comment]
これやりたい

**Comment by tuna2134** [comment]
> これやりたい

ふにゃ？
いいよ

**Comment by yaakiyu** [comment]
URLブロッカーと合わせてもいい気がしてきた
ちな、さっきcontributing.mdに書かれたんでどんなふうに作るか言っときますと
**ほぼ今までのRTと同じっす**
追加点としては、Exceptionsという例外指定のものを作り、
```json
{
    "channels": [...(例外チャンネル)],
    "roles": [...(規制対象のロールを持っていてもこっちのロールを持っている人は免れる)],
    "id": [...(いい名前が思いつかなかったけど、制限対象の人でも使える絵文字やスタンプ、リアクションのid)]
}
```みたいなの入れようかなーと思っております。
これ一応規制タイプ別に指定できるようにするつもりだけど、全タイプ一括でこういうのを指定できるオプションもあればいいなぁ、と思ってる。

**Comment by tasuren** [comment]
例外がまとめられたJSON取得するための例外ジェネレーターっていうコマンドを実装して、それで生成したJSONで指定するみたいなの良さそう。

**Comment by yaakiyu** [comment]
なるほど
例外ジェネレーターは別のPRで実装したいから例外に関しては今回は内部実装(DBに存在するだけ)だけでいいかな

**Comment by yaakiyu** [comment]
んで作ってて思ったけどRTEventってどう使うんだ..()

**Comment by yaakiyu** [comment]
なるほどなんとなくわかった(何も教えてもらってないけど自己学習完了(

**Comment by tasuren** [comment]
#36 とこれ統合するか。

**Comment by yaakiyu** [comment]
実装済みだったからcloseしようと思ったけど権限持ってないんだった()
