### ISSUE TITLE
音楽関連機能

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#85]
* [x] 音楽再生
  * [x] YouTube
  * [x] ニコニコ動画
  * [x] SoundCloud
  * [x] ~~Spotify~~ (時間が無いので後回し)
  * [x] ~~mp3/mp4~~
* [x] プレイリスト

**Comment by tuna2134** [comment]
@tasuren これどうする？

**Comment by tasuren** [comment]
Spotifyに関してはlibrespotっていうライブラリを使う予定でいる。

**Comment by tuna2134** [comment]
ふむ

**Comment by tasuren** [comment]
**実装するクラス**
- `Player`：サーバー毎に割り振るクラスで、音楽のキューや一時停止用の関数等を実装する。
- `Music`：音楽データ(`discord.FFmpegPCMAudio`等)を作る。また、どのくらい再生されたかを記録し、それを取得できるようにする。(`03:24`のように取得できるようにもする。)そして、`abc.ABC`クラスを継承する。(つまり、基底クラスである。)
  - YouTube等の動画配信サービス毎にこのクラスを継承したクラスを作る。そして、各サービス毎に別途必要なものを追加で実装する。

**Comment by tuna2134** [comment]
これやってもいいかも

**Comment by ysmreg** [comment]
これできなくはなさそうだけど認証前にやって大丈夫か心配ではある

**Comment by tuna2134** [comment]
もうすでに認証済みだが

**Comment by ysmreg** [comment]
Canalyを使うんじゃなくて前のRTのアカウントを使うの？

**Comment by tuna2134** [comment]
みたい

**Comment by ysmreg** [comment]
なるほど、それなら作り始めてもいいと思う

**Comment by tuna2134** [comment]
ああでもめんどくさそうだな
やめた()

**Comment by ysmreg** [comment]
音楽機能はかなり時間がかかるしめんどくさいよ

**Comment by tuna2134** [comment]
まあグローバルチャットが終わったらやるわ

**Comment by ysmreg** [comment]
まずはグローバルチャットだね

**Comment by tasuren** [comment]
これは僕がやる。
これと読みあげはtasurenクオリティにしたい。
あと、読みあげと音楽プレイヤー同時に使えるようにする予定。

**Comment by tuna2134** [comment]
ok

**Comment by tasuren** [comment]
実装した。
