### ISSUE TITLE
決済システムを作る。

### ISSUE THREAD

**Issue by tasuren** [RextTeam/rt-bot#87]
まだ具体的にStripeを使うかなど何を使うかが決まっていない。
候補：
* Stripe
* Patreon

**Comment by ysmreg** [comment]
Stripeなら作れるかもしれない、というか作ったことある別のbotで

**Comment by tasuren** [comment]
Stipeの予定
今のところ
Payments linkっていう便利なのあるからそれを使う。

**Comment by tasuren** [comment]
めんそくさいからpayments linkでいい

**Comment by ysmreg** [comment]
わかりました

**Comment by tuna2134** [comment]
うむ
Payment linksでいいと思う

**Comment by tasuren** [comment]
> わかりました

君が作るでOK？
もし作るならコンビニ決済も対応予定だか
、ら通常のwebhookのイベントと別のasyncなんたらっていうイベントも対応させてね。

**Comment by ysmreg** [comment]
コンビニ決済は仕組みがわからないんだよね。仕組みが分かれば作れるかもしれない

**Comment by ysmreg** [comment]
webhookの受信はWebサーバー建てないとかもしれなかったはず

**Comment by tasuren** [comment]
> webhookの受信はWebサーバー建てないとかもしれなかったはず

rt-backendにそれは実装すればいい。

**Comment by tasuren** [comment]
> コンビニ決済は仕組みがわからないんだよね。仕組みが分かれば作れるかもしれない

やるなら教えてね。

**Comment by tuna2134** [comment]
僕がやりたいと思っているが、環境的には難しいので誰か

**Comment by yaakiyu** [comment]
決済システムできたら
```py
from core import is_paid

#略

        @is_paid(level=2)
        @commands.command(...)
        async def command_name(self, ctx):
           ...
```
みたいな、課金者だけ使える機能みたいなのも実装できたらいいな

**Comment by tasuren** [comment]
wow

**Comment by tuna2134** [comment]
ふむ

**Comment by tasuren** [comment]
実装した。
